name: "publish release - Docker"

on:
  workflow_dispatch:
    inputs:
      is_release:
        required: false
        type: boolean
        description: "Is this a release image?"

  release:
    types: [published]

jobs:
  publish-docker-release:
    name: "publish to DockerHub"
    runs-on: ubuntu-22.04
    if: github.repository == 'microsoft/playwright-python'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: azure/docker-login@v1
      with:
        login-server: playwright.azurecr.io
        username: playwright
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker QEMU for arm64 docker builds
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - name: Install dependencies & browsers
      run: |
        python -m pip install --upgrade pip
        pip install -r local-requirements.txt
        pip install -e .
    - run: ./utils/docker/publish_docker.sh stable
      if: (github.event_name != 'workflow_dispatch' && !github.event.release.prerelease) || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_release == 'true')
    - run: ./utils/docker/publish_docker.sh canary
      if: (github.event_name != 'workflow_dispatch' && github.event.release.prerelease) || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_release != 'true')
